name: CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
      - uses: actions/checkout@v2

      - name: Print completion message
        run: echo Workflow complete!
